// <auto-generated />
using System;
using BlanquitaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlanquitaAPI.Migrations
{
    [DbContext(typeof(TacosBlanquitaContext))]
    [Migration("20231113050251_UpdateDatabase")]
    partial class UpdateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.Combo", b =>
                {
                    b.Property<int>("IdCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCombo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Total")
                        .HasColumnType("float");

                    b.HasKey("IdCombo")
                        .HasName("PK__Combo__D65BF2C8230EB487");

                    b.ToTable("Combo");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.Orden", b =>
                {
                    b.Property<int>("IdOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrden"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("IdOrden")
                        .HasName("PK__Orden__C38F300D645A4506");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Orden");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.OrdenCombo", b =>
                {
                    b.Property<int>("IdOrdenCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdenCombo"));

                    b.Property<int>("IdCombo")
                        .HasColumnType("int");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int");

                    b.HasKey("IdOrdenCombo")
                        .HasName("PK__OrdenCom__6BEFCB8B41CA470A");

                    b.HasIndex("IdCombo");

                    b.HasIndex("IdOrden");

                    b.ToTable("OrdenCombo");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerfil"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdPerfil")
                        .HasName("PK__Perfil__C7BD5CC117BA96DC");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdTipoProducto")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__098892104075B11C");

                    b.HasIndex("IdTipoProducto");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.ProductoCombo", b =>
                {
                    b.Property<int>("IdProductoCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductoCombo"));

                    b.Property<int>("IdCombo")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdProductoCombo")
                        .HasName("PK__Producto__87A1E832A9D2970E");

                    b.HasIndex("IdCombo");

                    b.HasIndex("IdProducto");

                    b.ToTable("ProductoCombo");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.TipoProducto", b =>
                {
                    b.Property<int>("IdTipoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoProducto"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoProducto")
                        .HasName("PK__TipoProd__A974F9200A83A316");

                    b.ToTable("TipoProducto");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF97F5C1BA4D");

                    b.HasIndex("IdPerfil");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.Orden", b =>
                {
                    b.HasOne("BlanquitaAPI.Data.BlanquitaModels.Usuario", "IdUsuarioNavigation")
                        .WithMany("Orden")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__Orden__IdUsuario__46E78A0C");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.OrdenCombo", b =>
                {
                    b.HasOne("BlanquitaAPI.Data.BlanquitaModels.Combo", "IdComboNavigation")
                        .WithMany("OrdenCombo")
                        .HasForeignKey("IdCombo")
                        .IsRequired()
                        .HasConstraintName("FK__OrdenComb__IdCom__4AB81AF0");

                    b.HasOne("BlanquitaAPI.Data.BlanquitaModels.Orden", "IdOrdenNavigation")
                        .WithMany("OrdenCombo")
                        .HasForeignKey("IdOrden")
                        .IsRequired()
                        .HasConstraintName("FK__OrdenComb__IdOrd__49C3F6B7");

                    b.Navigation("IdComboNavigation");

                    b.Navigation("IdOrdenNavigation");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.Producto", b =>
                {
                    b.HasOne("BlanquitaAPI.Data.BlanquitaModels.TipoProducto", "IdTipoProductoNavigation")
                        .WithMany("Producto")
                        .HasForeignKey("IdTipoProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Producto__IdTipo__398D8EEE");

                    b.Navigation("IdTipoProductoNavigation");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.ProductoCombo", b =>
                {
                    b.HasOne("BlanquitaAPI.Data.BlanquitaModels.Combo", "IdComboNavigation")
                        .WithMany("ProductoCombo")
                        .HasForeignKey("IdCombo")
                        .IsRequired()
                        .HasConstraintName("FK__ProductoC__IdCom__3E52440B");

                    b.HasOne("BlanquitaAPI.Data.BlanquitaModels.Producto", "IdProductoNavigation")
                        .WithMany("ProductoCombo")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__ProductoC__IdPro__3F466844");

                    b.Navigation("IdComboNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.Usuario", b =>
                {
                    b.HasOne("BlanquitaAPI.Data.BlanquitaModels.Perfil", "IdPerfilNavigation")
                        .WithMany("Usuario")
                        .HasForeignKey("IdPerfil")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario__IdPerfi__440B1D61");

                    b.Navigation("IdPerfilNavigation");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.Combo", b =>
                {
                    b.Navigation("OrdenCombo");

                    b.Navigation("ProductoCombo");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.Orden", b =>
                {
                    b.Navigation("OrdenCombo");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.Perfil", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.Producto", b =>
                {
                    b.Navigation("ProductoCombo");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.TipoProducto", b =>
                {
                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BlanquitaAPI.Data.BlanquitaModels.Usuario", b =>
                {
                    b.Navigation("Orden");
                });
#pragma warning restore 612, 618
        }
    }
}
